name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run presentation
        run: docker-compose up -d
      
      - name: Copy presentation files
        run: docker cp presentation:/reveal.js .
      
      - name: Push presentation to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: reveal.js
